name: coverage
on: [push, pull_request]
jobs:
  linux:
    name: linux
    runs-on: ubuntu-22.04
    steps:
      - name: Install ctags
        run: |
          sudo apt update && sudo apt install -y universal-ctags
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Vim
        uses: rhysd/action-setup-vim@v1
        id: vim
        with:
          version: v9.0.0000
      - name: Run Tests
        run: |
          uname -a
          export TAGLIST_PROFILE=1
          export VIMPRG=${{ steps.vim.outputs.executable }}
          $VIMPRG --version
          cd ./test
          ./run_tests.sh
      - name: Install Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.7.14
      - name: Install covimerage
        run: |
          pip install covimerage
          covimerage --version
      - name: Run covimerage
        run: |
          cd ./test
          covimerage write_coverage taglist_profile.txt
      - name: Take coverage
        run: |
          cd ./test
          coverage report
          coverage xml
      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./test/coverage.xml
